# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    pxe_install: "#{source_dir}"
  forge_modules:
    stdlib:           "puppetlabs/stdlib"
    concat:           "puppetlabs/concat"
    echo:             "ipcrm/echo"
    puppet_agent:     "puppetlabs/puppet_agent"
    facts:            "puppetlabs/facts"
    apache:           "puppetlabs/apache"
    samba:            "rehan/samba"
    augeas:           "puppetlabs/augeas_core"
    archive:          "puppet/archive"
    dhcp:             "puppet/dhcp"
